### PR TITLE
Add ip check to discovery setup script

### PR DESCRIPTION
**Pull request by raymondjacobson**
Requires https://github.com/AudiusProject/audius-protocol/pull/1316 to be merged & deployed first!

### CODE REVIEW

**Comment by dmanjunath** [comment]
Could you move this to the audius-k8s/ops/k8s-manifests folder?

**Review by cheran-senthil — COMMENTED** [review]
As Dheeraj mentioned, please make a PR to `audius-k8s` as well

**Review by cheran-senthil — APPROVED** [review]
Looks good to me, but we might want to merge with fresh updates of other things too.

**Comment by raymondjacobson** [comment]
> Looks good to me, but we might want to merge with fresh updates of other things too.

Will defer to whenever you want to!

**Comment by cheran-senthil** [comment]
Think we can merge and then refresh later 🚢

**Pull request merged**
